services:
  - type: web
    name: my-rails-app
    env: ruby
    plan: free
    region: oregon
    buildCommand: bundle install && rake db:migrate
    startCommand: rails server -b 0.0.0.0 -p $PORT
    autoDeploy: true
    branch: main
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: your-database-url
